name: Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@main
      - name: The work
        run: |
          sudo apt install -y libarchive-tools
          ./prepare-toolchain 5.7.2

      - name: Build package
        uses: L1ghtmann/theos-build@main
        with:
          extra_args: "FINALPACKAGE=1"

      - name: Attach Deb To Release
        run: |
          set -x
          TAG="${GITHUB_REF##*/}-${GITHUB_SHA:0:7}"
          gh release create "$TAG" --draft --title "Draft Release"
          gh release upload "$TAG" packages/*.deb
