name: Build

on:
  push:
    branches: [ linux-test ]
  pull_request:
    branches: [ linux-test ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: The work
        id: the_work
        run: |
          git clone https://github.com/mackyle/xar
          pushd xar/xar/
          sed -i 's@OpenSSL_add_all_ciphers@OPENSSL_init_crypto@' configure.ac
          ./autogen.sh
          make -j$(nproc --all)
          sudo make -j$(nproc --all) install
          popd
          sudo apt install -y libarchive-tools
          ./prepare-toolchain 5.7

      - name: Build package
        uses: L1ghtmann/theos-build@main

      - uses: actions/upload-artifact@main
        with:
          name: package
          path: packages/*.deb

  upload:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Download artifact
        uses: actions/download-artifact@main

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: 0.0.2
          release_name: Linux Trial 1
          draft: false
          prerelease: false

      - name: Attach deb to release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -x
          debs=()
          for deb in **/*.deb; do
            debs+=("-a" "$deb")
          done
          hub release edit "${debs[@]}" -m "Linux Trial 1" "0.0.2"
